package calculadora;

import javax.swing.JComponent;

public class For_Calculadora extends javax.swing.JFrame {
    Pantalla pantalla;
    Operaciones operacion = new Operaciones();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(For_Calculadora.class.getName());
    private Double numero1 = null;
    private Double numero2 = null;
    private Double respuesta = null;
    private String primeraOperacion = "";
    private String segundaOperacion = "";
    private boolean ultimoFueIgual = false;
    
    public For_Calculadora() {
        initComponents();
        this.pantalla = new Pantalla(jLabelPantalla);
        new Teclado((JComponent) this.getContentPane(), 
                jLabelPantalla, jBotonSumar, 
                jBotonRestar, jBotonMultiplicar, 
                jBotonDivision, jBotonIgual, 
                jBotonEliminar, jBotonPunto);
        this.setFocusable(true);
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonOff = new javax.swing.JButton();
        jBoton4 = new javax.swing.JButton();
        jBoton7 = new javax.swing.JButton();
        jBotonAC = new javax.swing.JButton();
        jBoton8 = new javax.swing.JButton();
        jBoton5 = new javax.swing.JButton();
        jBoton1 = new javax.swing.JButton();
        jBoton2 = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        jBoton9 = new javax.swing.JButton();
        jBoton6 = new javax.swing.JButton();
        jBoton3 = new javax.swing.JButton();
        jBotonDivision = new javax.swing.JButton();
        jBotonMultiplicar = new javax.swing.JButton();
        jBotonRestar = new javax.swing.JButton();
        jBotonSumar = new javax.swing.JButton();
        jBoton0 = new javax.swing.JButton();
        jBotonPunto = new javax.swing.JButton();
        jBotonIgual = new javax.swing.JButton();
        jLabelPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jBotonOff.setBackground(new java.awt.Color(51, 51, 51));
        jBotonOff.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonOff.setForeground(new java.awt.Color(255, 255, 255));
        jBotonOff.setText("OFF");
        jBotonOff.setAlignmentX(0.5F);
        jBotonOff.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBotonOff.setName(""); // NOI18N
        jBotonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonOffActionPerformed(evt);
            }
        });

        jBoton4.setBackground(new java.awt.Color(51, 51, 51));
        jBoton4.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton4.setForeground(new java.awt.Color(255, 255, 255));
        jBoton4.setText("4");
        jBoton4.setAlignmentX(0.5F);
        jBoton4.setName(""); // NOI18N
        jBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton4ActionPerformed(evt);
            }
        });

        jBoton7.setBackground(new java.awt.Color(51, 51, 51));
        jBoton7.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton7.setForeground(new java.awt.Color(255, 255, 255));
        jBoton7.setText("7");
        jBoton7.setAlignmentX(0.5F);
        jBoton7.setName(""); // NOI18N
        jBoton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton7ActionPerformed(evt);
            }
        });

        jBotonAC.setBackground(new java.awt.Color(51, 51, 51));
        jBotonAC.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonAC.setForeground(new java.awt.Color(255, 255, 255));
        jBotonAC.setText("AC");
        jBotonAC.setAlignmentX(0.5F);
        jBotonAC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBotonAC.setName(""); // NOI18N
        jBotonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonACActionPerformed(evt);
            }
        });

        jBoton8.setBackground(new java.awt.Color(51, 51, 51));
        jBoton8.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton8.setForeground(new java.awt.Color(255, 255, 255));
        jBoton8.setText("8");
        jBoton8.setAlignmentX(0.5F);
        jBoton8.setName(""); // NOI18N
        jBoton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton8ActionPerformed(evt);
            }
        });

        jBoton5.setBackground(new java.awt.Color(51, 51, 51));
        jBoton5.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton5.setForeground(new java.awt.Color(255, 255, 255));
        jBoton5.setText("5");
        jBoton5.setAlignmentX(0.5F);
        jBoton5.setName(""); // NOI18N
        jBoton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton5ActionPerformed(evt);
            }
        });

        jBoton1.setBackground(new java.awt.Color(51, 51, 51));
        jBoton1.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton1.setForeground(new java.awt.Color(255, 255, 255));
        jBoton1.setText("1");
        jBoton1.setAlignmentX(0.5F);
        jBoton1.setName(""); // NOI18N
        jBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton1ActionPerformed(evt);
            }
        });

        jBoton2.setBackground(new java.awt.Color(51, 51, 51));
        jBoton2.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton2.setForeground(new java.awt.Color(255, 255, 255));
        jBoton2.setText("2");
        jBoton2.setAlignmentX(0.5F);
        jBoton2.setName(""); // NOI18N
        jBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton2ActionPerformed(evt);
            }
        });

        jBotonEliminar.setBackground(new java.awt.Color(51, 51, 51));
        jBotonEliminar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jBotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBotonEliminar.setText("←");
        jBotonEliminar.setAlignmentX(0.5F);
        jBotonEliminar.setName(""); // NOI18N
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });

        jBoton9.setBackground(new java.awt.Color(51, 51, 51));
        jBoton9.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton9.setForeground(new java.awt.Color(255, 255, 255));
        jBoton9.setText("9");
        jBoton9.setAlignmentX(0.5F);
        jBoton9.setName(""); // NOI18N
        jBoton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton9ActionPerformed(evt);
            }
        });

        jBoton6.setBackground(new java.awt.Color(51, 51, 51));
        jBoton6.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton6.setForeground(new java.awt.Color(255, 255, 255));
        jBoton6.setText("6");
        jBoton6.setAlignmentX(0.5F);
        jBoton6.setName(""); // NOI18N
        jBoton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton6ActionPerformed(evt);
            }
        });

        jBoton3.setBackground(new java.awt.Color(51, 51, 51));
        jBoton3.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton3.setForeground(new java.awt.Color(255, 255, 255));
        jBoton3.setText("3");
        jBoton3.setAlignmentX(0.5F);
        jBoton3.setName(""); // NOI18N
        jBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton3ActionPerformed(evt);
            }
        });

        jBotonDivision.setBackground(new java.awt.Color(51, 51, 51));
        jBotonDivision.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonDivision.setForeground(new java.awt.Color(255, 255, 255));
        jBotonDivision.setText("/");
        jBotonDivision.setAlignmentX(0.5F);
        jBotonDivision.setName(""); // NOI18N
        jBotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDivisionActionPerformed(evt);
            }
        });

        jBotonMultiplicar.setBackground(new java.awt.Color(51, 51, 51));
        jBotonMultiplicar.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        jBotonMultiplicar.setText("x");
        jBotonMultiplicar.setAlignmentX(0.5F);
        jBotonMultiplicar.setName(""); // NOI18N
        jBotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMultiplicarActionPerformed(evt);
            }
        });

        jBotonRestar.setBackground(new java.awt.Color(51, 51, 51));
        jBotonRestar.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonRestar.setForeground(new java.awt.Color(255, 255, 255));
        jBotonRestar.setText("-");
        jBotonRestar.setAlignmentX(0.5F);
        jBotonRestar.setName(""); // NOI18N
        jBotonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRestarActionPerformed(evt);
            }
        });

        jBotonSumar.setBackground(new java.awt.Color(51, 51, 51));
        jBotonSumar.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonSumar.setForeground(new java.awt.Color(255, 255, 255));
        jBotonSumar.setText("+");
        jBotonSumar.setAlignmentX(0.5F);
        jBotonSumar.setName(""); // NOI18N
        jBotonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSumarActionPerformed(evt);
            }
        });

        jBoton0.setBackground(new java.awt.Color(51, 51, 51));
        jBoton0.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBoton0.setForeground(new java.awt.Color(255, 255, 255));
        jBoton0.setText("0");
        jBoton0.setAlignmentX(0.5F);
        jBoton0.setName(""); // NOI18N
        jBoton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton0ActionPerformed(evt);
            }
        });

        jBotonPunto.setBackground(new java.awt.Color(51, 51, 51));
        jBotonPunto.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonPunto.setForeground(new java.awt.Color(255, 255, 255));
        jBotonPunto.setText(".");
        jBotonPunto.setAlignmentX(0.5F);
        jBotonPunto.setName(""); // NOI18N
        jBotonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPuntoActionPerformed(evt);
            }
        });

        jBotonIgual.setBackground(new java.awt.Color(51, 51, 51));
        jBotonIgual.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jBotonIgual.setForeground(new java.awt.Color(255, 255, 255));
        jBotonIgual.setText("=");
        jBotonIgual.setAlignmentX(0.5F);
        jBotonIgual.setName(""); // NOI18N
        jBotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonIgualActionPerformed(evt);
            }
        });

        jLabelPantalla.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPantalla.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBoton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBoton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotonOff, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBoton0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonOff, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBoton0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBotonSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonOffActionPerformed

    }//GEN-LAST:event_jBotonOffActionPerformed

    private void jBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton4ActionPerformed
        pantalla.añadirTextoPantalla("4");
    }//GEN-LAST:event_jBoton4ActionPerformed

    private void jBoton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton7ActionPerformed
        pantalla.añadirTextoPantalla("7");
    }//GEN-LAST:event_jBoton7ActionPerformed

    private void jBotonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonACActionPerformed
        operar("AC");
    }//GEN-LAST:event_jBotonACActionPerformed

    private void jBoton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton8ActionPerformed
        pantalla.añadirTextoPantalla("8");
    }//GEN-LAST:event_jBoton8ActionPerformed

    private void jBoton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton5ActionPerformed
        pantalla.añadirTextoPantalla("5");
    }//GEN-LAST:event_jBoton5ActionPerformed

    private void jBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton1ActionPerformed
        pantalla.añadirTextoPantalla("1");
    }//GEN-LAST:event_jBoton1ActionPerformed

    private void jBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton2ActionPerformed
        pantalla.añadirTextoPantalla("2");
    }//GEN-LAST:event_jBoton2ActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
        String valor = jLabelPantalla.getText();
        if(!valor.isEmpty()){
            jLabelPantalla.setText(valor.substring(0, valor.length() - 1));
        }
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void jBoton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton9ActionPerformed
        pantalla.añadirTextoPantalla("9");
    }//GEN-LAST:event_jBoton9ActionPerformed

    private void jBoton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton6ActionPerformed
        pantalla.añadirTextoPantalla("6");
    }//GEN-LAST:event_jBoton6ActionPerformed

    private void jBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton3ActionPerformed
        pantalla.añadirTextoPantalla("3");
    }//GEN-LAST:event_jBoton3ActionPerformed

    private void jBotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDivisionActionPerformed
        operar("/");
    }//GEN-LAST:event_jBotonDivisionActionPerformed

    private void jBotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMultiplicarActionPerformed
        operar("*");
    }//GEN-LAST:event_jBotonMultiplicarActionPerformed

    private void jBotonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRestarActionPerformed
        operar("-");
    }//GEN-LAST:event_jBotonRestarActionPerformed

    private void jBotonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSumarActionPerformed
        operar("+");
    }//GEN-LAST:event_jBotonSumarActionPerformed

    private void jBoton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton0ActionPerformed
        pantalla.añadirTextoPantalla("0");
    }//GEN-LAST:event_jBoton0ActionPerformed

    private void jBotonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPuntoActionPerformed
        pantalla.añadirTextoPantalla(".");
    }//GEN-LAST:event_jBotonPuntoActionPerformed

    private void jBotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonIgualActionPerformed
        operar("igual");
    }//GEN-LAST:event_jBotonIgualActionPerformed

    private void operar(String op)
    {
        // Al precionar el boton AC se reinicia la calculadora a
        // valore por defecto, tanto en pantalla como en funcionamiento
        if (op == "AC")
        {
            setearValores();
            pantalla.limpiarPantalla();
            op = "";
            ultimoFueIgual = false;
            return;
        }
        // Valida para la primera operacion, si ya se realizo una anterior pasa al else
        if (numero1 == null || ultimoFueIgual)
        {
            numero1 = pantalla.obtenerUltimoNumero();
            primeraOperacion = op;
            ultimoFueIgual = false;
        }
        // Cuando se acumulan varias operaciones
        else
        {
            numero2 = pantalla.obtenerUltimoNumero();
            String operadorFinal = "";
            // Valida si es la primera o segunda operacion, cuandos se 
            // realizan varias operaciones en una linea
            if (segundaOperacion == "")
            {
                operadorFinal = primeraOperacion;
            }
            else
            {
                operadorFinal = segundaOperacion;
            }
            segundaOperacion = op;
            // Se realiza las operaciones programadas por defecto
            switch (operadorFinal)
            {
                case "+":
                    respuesta = operacion.sumar(numero1, numero2);
                break;
                case "-":
                    respuesta = operacion.restar(numero1, numero2);
                break;
                case "*":
                    respuesta = operacion.multiplicarar(numero1, numero2);
                break;
                case "/":
                    if (numero2==0)
                    {
                        pantalla.errorDivisionPorCero();
                        setearValores();
                        pantalla.limpiarPantalla();
                        return;
                    }
                    else
                    {
                        respuesta = operacion.dividir(numero1, numero2);
                    }
                break;
            }
            // coloca los valores en pantalla y se muestran valores de seguimiento en consola
            pantalla.ponerRespuesta(respuesta);
            System.out.println("'Numero 1' 'operador' 'Numero2' = 'resultado'");
            System.out.println(numero1 + operadorFinal + numero2 + "=" + respuesta);
            numero1 = respuesta;
        }
        // Si se preciona enter, se setea todo
        if (op == "igual")
        {
                pantalla.añadirTextoPantalla("");
                primeraOperacion = "";
                segundaOperacion = "";
                ultimoFueIgual = true;
        }
        // Si hay operacion, se muestra en pantalla
        else
        {
            pantalla.añadirTextoPantalla(op);
        }
        
    }
    // Reinicia todos los valores en pantalla
    public void setearValores()
    {
            numero1 = null;
            numero2 = 0.0;
            respuesta = 0.0;
            primeraOperacion = "";
            segundaOperacion = "";
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new For_Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton0;
    private javax.swing.JButton jBoton1;
    private javax.swing.JButton jBoton2;
    private javax.swing.JButton jBoton3;
    private javax.swing.JButton jBoton4;
    private javax.swing.JButton jBoton5;
    private javax.swing.JButton jBoton6;
    private javax.swing.JButton jBoton7;
    private javax.swing.JButton jBoton8;
    private javax.swing.JButton jBoton9;
    private javax.swing.JButton jBotonAC;
    private javax.swing.JButton jBotonDivision;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonIgual;
    private javax.swing.JButton jBotonMultiplicar;
    private javax.swing.JButton jBotonOff;
    private javax.swing.JButton jBotonPunto;
    private javax.swing.JButton jBotonRestar;
    private javax.swing.JButton jBotonSumar;
    private javax.swing.JLabel jLabelPantalla;
    // End of variables declaration//GEN-END:variables
}
